GAMES = [
  {
    'name': 'Fifa',
    'choices': [
      'Ajax',
      'Arsenal',
      'Atlético',
      'FC Barcelone',
      'Bayern',
      'Chelsea',
      'Dortmund',
      'Iter Milan',
      'Juventus',
      'Liverpool',
      'Man. City',
      'Man. United',
      'Napoli',
      'PSG',
      'Real Madrid',
      'Tottenham'
    ],
    'max': 2
  },
  {
    'name': 'NHL',
    'choices': [
      'Hurricanes',
      'Blue Jackets',
      'Devils',
      'Islanders',
      'Rangers',
      'Flyers',
      'Penguins',
      'Capitals',
      'Bruins',
      'Red Wings',
      'Panthers',
      'Canadiens',
      'Senators',
      'Lightning',
      'Maple Leafs',
      'Blackhawks',
      'Avalanche',
      'Wild',
      'Stars',
      'Predators',
      'Blues',
      'Jets',
      'Ducks',
      'Coyotes',
      'Flames',
      'Oilers',
      'Kings',
      'Canucks',
      'Golden Knights'
    ],
    'max': 2
  },
  {
    'name': 'Madden',
    'choices': [
      'Bills',
      'Dolphins',
      'Patriots',
      'Jets',
      'Ravens',
      'Bengals',
      'Browns',
      'Steelers',
      'Texans',
      'Colts',
      'Jaguars',
      'Titans',
      'Broncos',
      'Chiefs',
      'Chargers',
      'Raiders',
      'Cowboys',
      'Giants',
      'Eagles',
      'Redskins',
      'Bears',
      'Lions',
      'Packers',
      'Vikings',
      'Falcons',
      'Panthers',
      'Saints',
      'Buccaneers',
      'Cardinals',
      'Rams',
      '49ers',
      'Seahawks'
    ],
    'max': 2
  },
  {
    'name': 'Super Smash Bros',
    'choices': [
      'Mario',
      'Donkey Kong',
      'Link',
      'Samus Aran',
      'Dark Samus',
      'Yoshi',
      'Kirby',
      'Fox',
      'Pikachu',
      'Luigi',
      'Ness',
      'Captain Falcon',
      'Jigglypuff',
      'Peach',
      'Daisy',
      'Bowser',
      'Ice Climbers',
      'Sheik',
      'Zelda',
      'Dr. Mario',
      'Pichu',
      'Falco',
      'Marth',
      'Lucina',
      'Young Link',
      'Ganondorf',
      'Mewtwo',
      'Roy',
      'Chrom',
      'Mr. Game & Watch',
      'Meta Knight',
      'Pit',
      'Dark Pit',
      'Zero Suit Samus',
      'Wario',
      'Snake',
      'Ike',
      'Pokemon Trainer',
      'Diddy Kong',
      'Lucas',
      'Sonic',
      'King Dedede',
      'Olimar',
      'Lucario',
      'R.O.B.',
      'Toon Link',
      'Wolf',
      'Villager',
      'Mega Man',
      'Wii Fit Trainer',
      'Rosalina & Luma',
      'Little Mac',
      'Greninja',
      'Mii Fighter (Brawler)',
      'Mii Fighter (Swordfighter)',
      'Mii Fighter (Gunner)',
      'Palutena',
      'Pac-Man',
      'Robin',
      'Shulk',
      'Bowser Jr',
      'Duck Hunt',
      'Ryu',
      'Ken',
      'Cloud',
      'Corrin',
      'Bayonetta',
      'Inkling',
      'Ridley',
      'Simon',
      'Richter',
      'King K. Rool',
      'Isabelle',
      'Incineroar'
    ],
    'max': 4
  }
]